import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { SidebarInset } from "@/components/ui/sidebar";
import  AppSidebar  from "@/components/layout/AppSidebar";
import NavBar from "@/components/layout/NavBar";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} h-full antialiased font-sans`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <AppSidebar>
            <main className="flex min-w-0 flex-1 flex-col h-full">
              <NavBar/>
              <div className="flex-1 flex flex-col bg-white">{children}</div>
            </main>
        </AppSidebar>
      </body>
    </html>
  );
}
